export type UserRole = 'ADMIN' | 'MANAGER' | 'STAFF';

export type Permission =
  | 'POS_CHECKOUT'
  | 'VIEW_SALES'
  | 'VIEW_PRODUCTS'
  | 'MANAGE_PRODUCTS'
  | 'DELETE_PRODUCTS'
  | 'ADJUST_STOCK'
  | 'VIEW_CUSTOMERS'
  | 'MANAGE_CUSTOMERS'
  | 'RECORD_KHATA_PAYMENT'
  | 'OVERRIDE_CREDIT_LIMIT'
  | 'VIEW_SUPPLIERS'
  | 'MANAGE_SUPPLIERS'
  | 'CREATE_PURCHASES'
  | 'RECORD_SUPPLIER_PAYMENT'
  | 'PROCESS_RETURNS'
  | 'PROCESS_EXCHANGES'
  | 'APPLY_DISCOUNT'
  | 'APPLY_HIGH_DISCOUNT'
  | 'VIEW_EXPENSES'
  | 'MANAGE_EXPENSES'
  | 'VIEW_SALARIES'
  | 'APPROVE_SALARIES'
  | 'VIEW_FINANCIAL_REPORTS'
  | 'VIEW_AUDIT_LOGS'
  | 'MANAGE_USERS'
  | 'MANAGE_SETTINGS'
  | 'MANAGE_SCHEMA'
  | 'MANAGE_BACKUPS';

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  ADMIN: [
    'POS_CHECKOUT',
    'VIEW_SALES',
    'VIEW_PRODUCTS',
    'MANAGE_PRODUCTS',
    'DELETE_PRODUCTS',
    'ADJUST_STOCK',
    'VIEW_CUSTOMERS',
    'MANAGE_CUSTOMERS',
    'RECORD_KHATA_PAYMENT',
    'OVERRIDE_CREDIT_LIMIT',
    'VIEW_SUPPLIERS',
    'MANAGE_SUPPLIERS',
    'CREATE_PURCHASES',
    'RECORD_SUPPLIER_PAYMENT',
    'PROCESS_RETURNS',
    'PROCESS_EXCHANGES',
    'APPLY_DISCOUNT',
    'APPLY_HIGH_DISCOUNT',
    'VIEW_EXPENSES',
    'MANAGE_EXPENSES',
    'VIEW_SALARIES',
    'APPROVE_SALARIES',
    'VIEW_FINANCIAL_REPORTS',
    'VIEW_AUDIT_LOGS',
    'MANAGE_USERS',
    'MANAGE_SETTINGS',
    'MANAGE_SCHEMA',
    'MANAGE_BACKUPS',
  ],
  MANAGER: [
    'POS_CHECKOUT',
    'VIEW_SALES',
    'VIEW_PRODUCTS',
    'MANAGE_PRODUCTS',
    'ADJUST_STOCK',
    'VIEW_CUSTOMERS',
    'MANAGE_CUSTOMERS',
    'RECORD_KHATA_PAYMENT',
    'VIEW_SUPPLIERS',
    'MANAGE_SUPPLIERS',
    'CREATE_PURCHASES',
    'RECORD_SUPPLIER_PAYMENT',
    'PROCESS_RETURNS',
    'PROCESS_EXCHANGES',
    'APPLY_DISCOUNT',
    'APPLY_HIGH_DISCOUNT',
    'VIEW_EXPENSES',
    'MANAGE_EXPENSES',
    'VIEW_SALARIES',
    'APPROVE_SALARIES',
    'VIEW_FINANCIAL_REPORTS',
  ],
  STAFF: [
    'POS_CHECKOUT',
    'VIEW_SALES',
    'VIEW_PRODUCTS',
    'VIEW_CUSTOMERS',
    'MANAGE_CUSTOMERS',
    'RECORD_KHATA_PAYMENT',
    'APPLY_DISCOUNT',
  ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  const allowed = ROLE_PERMISSIONS[role];
  if (!allowed) return false;
  return allowed.includes(permission);
}
